---
title: "text_from_pdf"
author: "Ravi Hela"
date: "25/08/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

myfiles <- list.files(path = "C:/Users/Rabi/Documents/Data_Science/pdf_test", pattern = "pdf",  full.names = TRUE)

convert_to_image <- function(x) {
  pdftools::pdf_convert(x, dpi = 600)
}

image_files <- lapply(myfiles, convert_to_image)

convert_text <- function(img_file) {
  tesseract::ocr(img_file)
}

text_converted <- sapply(unlist(image_files), convert_text)

word_df <- as.data.frame(text_converted) %>%
  rownames_to_column() %>%
  mutate(rowname = str_remove(rowname, ".png")) %>%
  mutate(page = str_extract(rowname, "[0-9]$|[0-9]+[0-9]+$")) %>%
  unnest_tokens(word, text_converted) %>%
  filter(str_detect(rowname, "ey-future" )) %>%
  anti_join(stop_words)

word_df %>%
  count(word, sort = TRUE) %>%
  filter(n > 50) %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n)) +
  geom_col() +
  xlab(NULL) +
  coord_flip()

word_df %>%
  inner_join(get_sentiments()) %>% 
  group_by(page, sentiment) %>% count() %>%
  pivot_wider(names_from = sentiment, values_from = n, values_fill = 0) %>%
  mutate(page = as.numeric(page)) %>% arrange((page)) %>%
  mutate(score = positive - negative) %>%
  ggplot(aes(x = page, y = score)) + geom_col() + theme_minimal()
  


```

